version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: joplin-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /mnt/joplin-usb/postgres-backup:/backup
    networks:
      - joplin-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Joplin Server
  joplin:
    image: joplin/server:latest
    container_name: joplin-server
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      APP_PORT: 22300
      APP_BASE_URL: https://joplin.${DOMAIN_NAME}
      DB_CLIENT: pg
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      MAILER_ENABLED: 1
      MAILER_HOST: ${SMTP_HOST}
      MAILER_PORT: ${SMTP_PORT}
      MAILER_SECURITY: ${SMTP_SECURITY}
      MAILER_AUTH_USER: ${SMTP_USER}
      MAILER_AUTH_PASSWORD: ${SMTP_PASSWORD}
      MAILER_NOREPLY_NAME: ${MAILER_NOREPLY_NAME}
      MAILER_NOREPLY_EMAIL: ${MAILER_NOREPLY_EMAIL}
    volumes:
      - /mnt/joplin-usb/joplin-data:/joplin
    ports:
      - "22300:22300"
    networks:
      - joplin-network

  # MotionEye Camera System
  motioneye:
    image: ccrisan/motioneye:master-amd64
    container_name: motioneye-camera
    restart: unless-stopped
    environment:
      - TZ=${TIMEZONE}
    volumes:
      - ./config/motioneye:/etc/motioneye
      - /mnt/joplin-usb/camera-data:/var/lib/motioneye
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8765:8765"
    devices:
      - /dev/video0:/dev/video0
    networks:
      - joplin-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    depends_on:
      - joplin
      - motioneye
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites-available:/etc/nginx/sites-available:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - /mnt/joplin-usb/nginx-logs:/var/log/nginx
    networks:
      - joplin-network

  # Fail2ban Security
  fail2ban:
    image: crazymax/fail2ban:latest
    container_name: fail2ban-security
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./config/fail2ban:/data
      - /mnt/joplin-usb/nginx-logs:/var/log/nginx:ro
      - /var/log:/var/log:ro
    environment:
      - TZ=${TIMEZONE}
      - F2B_LOG_LEVEL=INFO
      - F2B_DB_PURGE_AGE=1d

networks:
  joplin-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/joplin-usb/postgres-data
